<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  ~ Copyright (c) 2024. NittenApps
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.nittenapps</groupId>
    <artifactId>parent</artifactId>
    <version>5-SNAPSHOT</version>
  </parent>

  <groupId>dev.nittenapps.stack</groupId>
  <artifactId>stack</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>NittenApps :: Stack</name>
  <url>${docs.url}/${project.artifactId}</url>
  <inceptionYear>2024</inceptionYear>

  <scm>
    <developerConnection>scm:git:${git.url}/${git.repo}.git</developerConnection>
    <url>${git.url}/${git.repo}</url>
  </scm>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>

    <git.repo>stack</git.repo>
    <jira.key>STCK</jira.key>
  </properties>

  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
      <id>NittenApps Snapshots</id>
      <name>NittenApps Apache Maven Repository</name>
      <url>https://repo.nittenapps.dev/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
    <repository>
      <id>NittenApps Releases</id>
      <name>NittenApps Apache Maven Repository</name>
      <url>https://repo.nittenapps.dev/releases</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
    <repository>
      <id>osgeo</id>
      <name>OSGeo Release Repository</name>
      <url>https://repo.osgeo.org/repository/release/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <releases>
        <enabled>true</enabled>
      </releases>
    </repository>
  </repositories>

  <modules>
    <module>parent</module>
    <module>bom</module>
    <module>api</module>
    <module>files</module>
    <module>core</module>
    <module>config</module>
    <module>activity</module>
    <module>flowable</module>
    <module>keycloak</module>
    <module>spatial</module>
    <module>spring-boot-starter</module>
    <module>dependencies</module>
  </modules>
</project>